version: '3.8'
name: javateam11

services:
  # MySQL 데이터베이스
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: classroom_reservation
      MYSQL_USER: classroom_reservation
      MYSQL_PASSWORD: Knu2025java11!
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

  # Spring Boot 애플리케이션
  backend:
    build: .
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/classroom_reservation?serverTimezone=Asia/Seoul
      SPRING_DATASOURCE_USERNAME: classroom_reservation
      SPRING_DATASOURCE_PASSWORD: Knu2025java11!
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true
    networks:
      - web
    restart: unless-stopped

volumes:
  mysql_data:
    driver: local

networks:
  web:
    external: true