spring:
  datasource:
    url: jdbc:mysql://nitro.inft.kr:3306/classroom_reservation?serverTimezone=Asia/Seoul
    username: classroom_reservation
    password: Knu2025java11!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    user:
      name: admin
      password: admin
# JWT 설정
jwt:
  secret: RjK/pKVFsBiRdPNYq1xw3BkgPjAE71o0+3LnaP8L/ws=
  expiration: 3600000 